/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'PC' at '11/5/15 11:55 AM' with Gradle 2.6
 *
 * @author PC, @date 11/5/15 11:55 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
